# 3. Introducción a NumPy
NumPy es una librería que nos permite un manejo eficiente de arreglos extremadamente grandes, los guales sustituyen a las listas de Python (solo para manejar listas como arreglos o vectores).

El arreglo de NumPy es una forma multidimensional que puede ser manipulada como un arreglo de 1-D, 2-D, 3-D, etc. La idea es que Numpy trabaje nuestros datos de forma más eficiente que las listas de Python, ya que tiene interoperabilidad con librerías de C.

Vamos a ver lo más importante de NumPy basándonos en el siguiente tutorial, siguiendo la documentación oficial.

In [38]:
import numpy as np
import matplotlib.pyplot as plt

a=np.array([[1.,2.,3.], [2.,4.,6.]]) #arreglo de Numpy

size=a.size #número de elementos
shape=a.shape #dimensiones del arreglo
dim=a.ndim #npumero de ejes

print (a)
print ("size =", size, "|| shape =", shape, "|| ndim =", dim)

[[1. 2. 3.]
 [2. 4. 6.]]
size = 6 || shape = (2, 3) || ndim = 2


In [18]:
a1=np.array([2,4,6])
print(a1)
print(type(a1))
print(a1.dtype)
print(a1.itemsize)
print("Bytes size: {} bytes".format(a1.size * a1.itemsize))

[2 4 6]
<class 'numpy.ndarray'>
int32
4
Bytes size: 12 bytes


In [25]:
a2=np.arange(100)
a3=np.zeros((2,3))
print(a3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [33]:
im=np.zeros((10,10,3))
#print(im)

In [29]:
v1=np.arange(10,20)
print (v1)

[10 11 12 13 14 15 16 17 18 19]


In [32]:
m1=np.arange(1,17).reshape(4,4) #darle una nueva forma a un arreglo lineal a una matriz de 4x4
print(m1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


#### Crear matrices con números aleatorios

In [49]:
v2=np.random.randn(10)
x=np.array([1,2,3,4,5,6,7,8,9,10])
print(v2)
#plt.plot(x,v2)

[-1.19495549  2.46554992 -0.11388283  1.38245494 -1.00985259 -0.92990735
 -1.59247234 -1.3797211  -0.54886408 -0.458264  ]


In [42]:
v=np.random.uniform(1,3,5) #5 muestras aleatorias entre 1 y 3
print(v)

[1.233539   2.75088404 2.91031523 1.4877576  2.43468743]


In [48]:
im=np.random.randint(0,256,2*2*3). reshape(2,2,3)
print(im)

[[[ 61 130  19]
  [213 186 118]]

 [[197  78 210]
  [199  98 153]]]


In [51]:
v=np.random.choice([1,4,9],6)
print(v)

[1 4 9 9 9 1]


In [60]:
v=np.random.normal(4,0.8,[2,3])
print(v)
#print(sum(v)/len(v)) #media del arreglo
#plt.plot(v)

[[2.90954398 4.14586682 2.07465596]
 [5.07279295 3.60162284 5.01651573]]
